### ISSUE TITLE
Follow-up on upper-limits with toys

### ISSUE THREAD

**Issue by luilongo** [histfitter/histfitter#100]
Issue opened on [root github](https://github.com/root-project/root/issues/9196)

**Comment by luilongo** [comment]
The memory leak will be fixed as soon as  the root [request 8324](https://github.com/root-project/root/pull/8324)  will be done, as reported by Jonas [1](https://github.com/root-project/root/issues/9196#issuecomment-969253664). 
This issue will be closed after having checked there is no memory leak on HF routine.

**Comment by kratsg** [comment]
linking root-project/root#8324 and root-project/root#9196

**Comment by guitargeek** [comment]
Hello! This issue should be fixed now in ROOT master.

**Comment by luilongo** [comment]
Hello @guitargeek , thanks a lot for all the help. We will check it with the new root rel

**Comment by guitargeek** [comment]
You're welcome! The fix will be included in 6.28, so you'd need to wait a couple of months to have it in a release.

**Comment by longjon929** [comment]
Hi,

This took a little while, but I finally managed to test this with a newer version of ROOT and the changes in #137.
You can see that the memory usage with 6.26/08 on my laptop is dramatically lower than 6.24/00 on lxplus:
![image](https://user-images.githubusercontent.com/1594459/212072085-c0d9dd3b-7c44-439c-8360-6857620b1735.png)
This is using `HistFitter.py -l analysis/tutorial/MyUserAnalysis.py` (an upper limit scan) with 5k toys per point.  I killed the lxplus jobs when they were about halfway through the mu scan.

Thanks again @guitargeek !

Best,
Jonathan
