### ISSUE TITLE
Fix harvestToContours.py for Root 6.22

### ISSUE THREAD

**Issue by sarahlouisewilliams** [histfitter/histfitter#112]
When testing the harvestToContours.py script in the python 2.X branch (v0.66.0) I noticed that for ROOT versions >=6.22 ROOT.Double() cannot be used to pass by reference. Instead we need to import ctypes and then change L791/2 to:
        tmpx, tmpy = ctypes.c_double(1.), ctypes.c_double(1.)
        tmpx1, tmpy1 = ctypes.c_double(1.), ctypes.c_double(1.)
I haven't tested if this would work in previous versions of ROOT, and am not sure whether we want to change this in master?
I am happy to try to do a MR for this but need to work out how best to do it...
Sarah Williams

**Comment by longjon929** [comment]
Hi @sarahlouisewilliams , Matthew replaced ROOT.Double in this commit https://github.com/histfitter/histfitter/commit/c7d6c5ca3366c6d200c94f15bcbcea666e0b0790#diff-d16fb04018c8227bd7c7f5f97abab11eba14eaa0b49786f6a3ece2ee755f83c9 around December 2020.

**Comment by sarahlouisewilliams** [comment]
Amazing- thanks @longjon929 -
Is there a reason it didn't make it into v0.66.0?
I wonder if we should change the recommended ROOT version for that if not?

**Comment by longjon929** [comment]
If I had to guess, it's because Matthew's work to update HF to python 3 was a separate branch from the old python 2 code.  Something should be added to the README at least for posterity, but in general it would be best to use the updated python 3 version.

**Comment by matthewfeickert** [comment]
> Is there a reason it didn't make it into v0.66.0?

@sarahlouisewilliams The migration work to move from Python 2 to Python 3.6+ was done back when HistFitter lived on GitLab, so please see [Issue 15](https://gitlab.cern.ch/HistFitter/HistFitter/-/issues/15) and [MR 70](https://gitlab.cern.ch/HistFitter/HistFitter/-/merge_requests/70) there for specifics. The short answer to your question though is that `v0.66.0` was requested to be a final release that was Python 2 only which had been tested only on pre `v6.20` releases of ROOT given multiple problems with later releases. Given this, [GitLab MR 70](https://gitlab.cern.ch/HistFitter/HistFitter/-/merge_requests/70) became release [`v1.0.0`](https://github.com/histfitter/histfitter/releases/tag/v1.0.0) which was compliant with Python 3.6+ and modern ROOT releases.

> I wonder if we should change the recommended ROOT version for that if not?

I believe that @longjon929's suggestion of

> but in general it would be best to use the updated python 3 version.

is the reasonable thing to do here. While I appreciate that people are still locked into Python 2 only situations for some analysis reasons, I don't think that it is reasonable to expect that legacy releases of HistFitter work with modern ROOT given there are substantial changes (that break SemVer) throughout ROOT's releases. So if possible, please migrate to Python 3 if you want to use HistFitter and modern ROOT.

I'll leave it up to the @histfitter/developers though on what legacy support actions they wish to do.
