### ISSUE TITLE
Integrate cmake

### ISSUE THREAD

**Issue by fixgoats** [histfitter/histfitter#120]
Hi all. I don't think I need to convince anyone here of the value of Cmake. I've made a CMakeLists that seems to generate an equivalent library to the Makefile after running it on the tests and tutorials, and hopefully someone can check if it works on more systems. Since the CMakeLists wound up not being very long I'll just include it in the issue for easy copy-pasting, and with some comments.
```
# An earlier version would work with this file, but 3.21 introduces some nice
# features to cmake-presets.
cmake_minimum_required(VERSION 3.21)

project(HistFitter VERSION 1.0.2)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# Original Makefile specifically added Html for Windows and not for Linux or
# macOS/OSX. Not sure why it's needed on Windows but not the other platforms,
# but I don't have a Windows machine and if it's in the Makefile I'm not going to argue with that.
set(root_components Core;Net;Hist;Graf;Graf3d;Gpad;Tree;Rint;
        Postscript;Matrix;Physics;Gui;RooFitCore;RooFit;RooStats;
        HistFactory;XMLParser;Foam;Html;Minuit)

# The Makefile has some code for ROOT 5, but one: it also requires C++17
# and was there really any release of ROOT 5 compiled with C++17?
# And two: if someone is still using ROOT 5, wouldn't they just use the old
# python 2 branch anyway?
find_package(ROOT 6 REQUIRED ${root_components})
list(TRANSFORM root_components PREPEND ROOT::)

set(local_libs ChannelStyle;CombinationUtils;CombineWorkSpaces;ConfigMgr;
        DrawUtils;FitConfig;HistogramPlotter;HypoTestTool;json;LimitResult;
        RooExpandedFitResult;RooHist;RooPlot;Significance;StatTools;
        TEasyFormula;TMsgLogger;toy_utils;Utils;ValidationUtils;XtraValues)
list(TRANSFORM local_libs APPEND .h OUTPUT_VARIABLE headers)
list(TRANSFORM local_libs APPEND .cxx OUTPUT_VARIABLE local_lib_sources)

add_library(SusyFitter SHARED ${local_lib_sources})
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)

# On my system, Cmake threw an error complaining I needed to link OpenMP
# and MPI, even though the Makefile doesn't link either and compiles  just fine.
# This may just be distribution specific, but hopefully adding these as optional
# dependencies fixes that in general.
find_package(OpenMP)
find_package(MPI)

# In 99.99% of cases link time optimization is a safe and easy performance gain, but in
# a few exceptional cases it can cause subtle bugs.
include(CheckIPOSupported)
check_ipo_supported(RESULT supported OUTPUT error)
if(CMAKE_BUILD_TYPE STREQUAL Release)
    if(supported)
        message(STATUS "LTO/IPO enabled")
        set_property(TARGET SusyFitter PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
    else()
        message(STATUS "LTO/IPO not supported: <${error}>")
    endif()
endif()

target_link_libraries(SusyFitter PRIVATE ${root_components} Threads::Threads  m dl)
if(OpenMP::OpenMP_CXX)
    target_link_libraries(SusyFitter PRIVATE OpenMP::OpenMP_CXX)
endif()
if(MPI::MPI_CXX)
    target_link_libraries(SusyFitter PRIVATE MPI::MPI_CXX)
endif()
set_property(TARGET SusyFitter PROPERTY POSITION_INDEPENDENT_CODE ON)
#required to make ROOT_GENERATE_DICTIONARY work
target_include_directories(SusyFitter PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
ROOT_GENERATE_DICTIONARY(SusyFitter_dict ${headers} MODULE HistFitter LINKDEF LinkDef.h)
```
Creating CMakeLists.txt with this content in `src` and running `cmake src -B lib` (and adding `-DCMAKE_BUILD_TYPE=Release` for performance. As far as I can tell the original Makefile actually only applies -O2 and includes debug symbols, whereas the release build type on Cmake applies -O3 and does no debug.) and then `cmake --build lib` from the root directory should work in place of the Makefile.

**Comment by longjon929** [comment]
Hi @fixgoats ,

Thanks for starting this.  I think upgrading to cmake will make it easier to get HistFitter compiled into an internal ATLAS release.  So it was convenient timing that you set this up.  Could you put this into a pull request so it's easy to pull and test?

I can't say I've looked at cmake for a little bit, but it looks like you're writing out the various source files?  There must be a way to grep everything?

What system are you testing on?

**Comment by fixgoats** [comment]
Pull request has been created. I'm using Arch Linux with ROOT 6.26.

As for writing out files, this is possible with globbing but Cmake itself [advises against this and recommends that source files be written out explicitly](https://cmake.org/cmake/help/v3.15/command/file.html?highlight=glob#filesystem). There's also [this discussion on stackoverflow](https://stackoverflow.com/questions/1027247/is-it-better-to-specify-source-files-with-glob-or-each-file-individually-in-cmak/18538444#18538444).

**Comment by longjon929** [comment]
I've tested this on lxplus and it seems to be working ok.

**Comment by matthewfeickert** [comment]
Quoting https://github.com/histfitter/histfitter/pull/121#issuecomment-1188631383:

> We're going to need to set up a GitHub actions to run the cmake configuration so we know that things work well. If @fixgoats is familiar enough with GHA to do this, then feel free to add it in this PR. Otherwise, either @matthewfeickert or myself can do it in a follow-up PR.

@kratsg can you (or @longjon929) make a follow up Issue for this? I won't be able to look at this until 2022-07-25 at the earliest, but I suspect that @kratsg is in a similar position given ICHEP.
