### ISSUE TITLE
Missing data file for example code

### ISSUE THREAD

**Issue by abdusa1am** [histfitter/histfitter#131]
Hi all!
I want to run `HistFitter.py -w analysis/tutorial/MySimpleChannelConfig.py`, but error occurs after excution. It seems that data file for this code is missing. Can someone make up it ? thanks in advance.

**Comment by longjon929** [comment]
Hello @abdusa1am ,

Could you please give us a few more details about your setup?  Are you following the tutorial?  If I had to guess you're missing the data file from that.  I'm not sure if it's publicly accessible outside of ATLAS at the moment.

**Comment by abdusa1am** [comment]
Thanks for your quick reply. 
I am following the tutorial in [this site](https://twiki.cern.ch/twiki/bin/view/Main/HistFitterTutorialOutsideAtlas). I tried several example code, they all can be sucessfully excuted, but `analysis/tutorial/MySimpleChannelConfig.py` this one is not, In part 5 they wrote :
> We have already run the -t step for you, so you only need to construct the workspaces, but first copy the histograms file to the data/ directory
>  `cp samples/tutorial/MySimpleChannelAnalysis.root data/`

But there is no folder named `samples`. That is why I assumed this data file is probably missing.

**Comment by abdusa1am** [comment]
Another missing file is `Sig_SU_400_500_0_10_P_combined_NormalMeasurement_model.root` in this [code example](https://github.com/histfitter/histfitter/blob/master/macros/Examples/pythonFreeConfig/Config_pythonFree.C)

**Comment by longjon929** [comment]
Hi @abdusa1am,

Ok, the issue is that the example files aren't linked on the external tutorial twiki.  They're available here: /afs/cern.ch/atlas/project/PAT/tutorial/cern-oct2014/HistFitter
Looking at the permissions it seems like it should be visible to anyone.  You'll just need to copy files to the appropriate place.  These are the relevant bits:
```
export ALRB_TutorialData=/afs/cern.ch/atlas/project/PAT/tutorial/cern-may2015
mkdir samples
cd samples
ln -s $ALRB_TutorialData/HistFitter tutorial
```


For the second one, I'm not aware of any example files for it.  I believe that script is just meant to be an example where you could put your own workspace.  I would suggest sticking with the python-based config.

**Comment by abdusa1am** [comment]
Hi @longjon929 ,
Thank you very much! I got the data file. By the way, I need a simple example script that plot the before and after fit plots, using external workspace file as input, generate by ROOT histfacory class but not by HistFitter.py.  Is there any example script like [this one](https://github.com/histfitter/histfitter/blob/master/macros/Examples/pythonFreeConfig/Config_pythonFree.C) with data file.

**Comment by longjon929** [comment]
Hi @abdusa1am,

I'm not aware of any generic scripts.  You can in principle use the function in HistFitter that is used for plotting, but you might need to make sure that the names of objects in your workspace follow the convention it expects.  For example take a look at here https://github.com/histfitter/histfitter/blob/master/src/Utils.cxx#L199 you see that it expects the workspace to be named 'combined'.  That script you point to is essentially telling you how to call the function that will run a fit and make the plots.  

If you want to be more direct, I think HistogramPlotter is doing the plotting.  Search for that or PlotPdfWithComponents

This root forum post might also be useful for you:
https://root-forum.cern.ch/t/extracting-histograms-from-histfactory-generated-rooworkspace/39808/2

**Comment by kratsg** [comment]
You can use cabinetry + pyhf to do this if you have just a HistFactory workspace, using `pyhf xml2json` to convert over to the JSON workspace and then cabinetry to make the plots.
