### ISSUE TITLE
Wrong yields if region name includes the string "{sample}_"

### ISSUE THREAD

**Issue by jeanyvesb9** [histfitter/histfitter#142]
Due to the changes in Commit #137 to the way the `Utils::GetComponent` (and also `Utils::GetComponentFractionInRegion`, although this last function is not used anywhere...) function works, the wrong components can be matched if the region name includes the substring `f"{sample}_"` (e.g. a region named "CRttbar", and a sample named "ttbar"):

```
...

TString target = componentVec[iComp]+"_";
if(  regionCompNameVec[iReg].Contains(target.Data()) {

...
```

In the analysis I'm working on, all components are named `f"{sample}_{regionFullName}_shapes"`. For example, see the following excerpt from the log:

```
<INFO> Util:  GetComponent: regionCompNameVec[0] = ttbar_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[1] = SingleTop_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[2] = ttW_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[3] = ttZ_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[4] = ttee_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[5] = ttmumu_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[6] = tttautau_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[7] = threetop_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[8] = fourtop_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[9] = ZjetsMuMu_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[10] = ZjetsEE_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[11] = ZjetsTauTau_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[12] = WjetsMunu_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[13] = WjetsEnu_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[14] = WjetsTaunu_CRttbar_cuts_shapes componentVec[0] = ttbar
<INFO> Util:  GetComponent: regionCompNameVec[15] = Diboson_CRttbar_cuts_shapes componentVec[0] = ttbar
```

It seems this issue could be solved simply by replacing [line 2117 of Utils.cxx](https://github.com/histfitter/histfitter/blame/master/src/Utils.cxx#L2117) by
```
...

TString target = componentVec[iComp]+"_"+regionFullName;

...
```
(and also in lines [2215](https://github.com/histfitter/histfitter/blame/master/src/Utils.cxx#L2215) and [2238](https://github.com/histfitter/histfitter/blame/master/src/Utils.cxx#L2238) to fix the same potential issue in `Utils::GetComponentFracInRegion`), but I'm not sure if this could cause an impact on some more complex cases (like multi-bin hists). If @longjon929 thinks this is ok, I'll create a merge request of this fix.

**Comment by longjon929** [comment]
Hi @jeanyvesb9 ,

Thanks for trying the updates and reporting with details.  That sounds like it should work.  Please go ahead and open a merge request.  Could you please try the tutorial multibin fit below to test.  There was something weird about the naming for multibin channels, but I don't remember where that was at the moment.  


https://github.com/histfitter/histfitter/blob/master/analysis/tutorial/MyUserAnalysis_ShapeFactor.py 
and dumping the yields:
YieldsTable.py  -c SR -w results/MyUserAnalysis_ShapeFactor/SPlusB_combined_NormalMeasurement_model_afterFit.root -s Bkg,DataDriven,Sig -o yields.tex

This is what I get now if it's useful:
<INFO> YieldsTable: Will dump output dictionary:
<INFO> YieldsTable: Fitted_err_Bkg: [1.986730476159721]
<INFO> YieldsTable: Fitted_err_DataDriven: [11.23293413394978]
<INFO> YieldsTable: Fitted_err_Sig: [4.5000089999910005]
<INFO> YieldsTable: Fitted_events_Bkg: [40.00170386144762]
<INFO> YieldsTable: Fitted_events_DataDriven: [69.99132752960129]
<INFO> YieldsTable: Fitted_events_Sig: [90.0]
<INFO> YieldsTable: MC_exp_err_Bkg: [2.0]
<INFO> YieldsTable: MC_exp_err_DataDriven: [nan]
<INFO> YieldsTable: MC_exp_err_Sig: [4.5000089999910005]
<INFO> YieldsTable: MC_exp_events_Bkg: [40.0]
<INFO> YieldsTable: MC_exp_events_DataDriven: [2.0]
<INFO> YieldsTable: MC_exp_events_Sig: [90.0]
<INFO> YieldsTable: TOTAL_FITTED_bkg_events: [199.99303139104887]
<INFO> YieldsTable: TOTAL_FITTED_bkg_events_err: [11.93434558848553]
<INFO> YieldsTable: TOTAL_MC_EXP_BKG_err: [nan]
<INFO> YieldsTable: TOTAL_MC_EXP_BKG_events: [132.0]
<INFO> YieldsTable: names: ['SR']
<INFO> YieldsTable: nobs: [200.0]

**Comment by jeanyvesb9** [comment]
Tried it, and got the same yields reported :)
I just made the pull request
