### ISSUE TITLE
Changes Required for ROOT v6.28

### ISSUE THREAD

**Issue by jeanyvesb9** [histfitter/histfitter#146]
Given the changes to RooFit implemented in ROOT v6.28 (https://root-forum.cern.ch/t/minimized-nll-not-corresponding-to-best-chi2/50120), I think it's a priority that we upgrade HistFitter to the new ROOT release. However, this means some breaking changes that need to be addressed:

- Removal of `RooList`: This is a core part of the `RooPlot` and `RooHist` custom implementations in HistFitter (based on a very old ROOT release), required to produce the ratio plots not available by default in the ROOT classes. However, the ratio plots can be produced with a function from the default RooPlot implementation, eliminating the need for additional code in HistFitter's repository.
- Removal of the already deprecated "Const" field from the NormFactor tags in the XMLs used as an input to `hist2workspace`; the tool crashes if the "Const" field is present.
- Removal of the custom `getPropagatedError628` implementations: this would represent a breaking change, requiring ROOT v6.28 to run HistFitter. However, given the improvements to RooFit in 6.28, I would strongly suggest breaking compatibility in r1.2.0 with any older ROOT release.

@longjon929 I've already implemented the first two changes, and have them working locally, observing the same results from the fits as in previous versions. I'll work today on implementing the third change, and will submit a MR.

**Comment by jeanyvesb9** [comment]
Done! I'll try to push the third change in the next hours

**Comment by jeanyvesb9** [comment]
Hey! The last thing that we're missing regarding this issue is creating the tag for v1.2.0. It's already referenced everywhere in the README.md and in the setup

**Comment by longjon929** [comment]
@jeanyvesb9 Yes, I updated the tag a bit preemptively.  I wasn't sure if there was a bug to fix based on some problems a user was having.  I'd like to just run a couple of tests before tagging, but updating to a new ROOT on my laptop is slow.
