### ISSUE TITLE
Adding histoSysEnvelope functionality 

### ISSUE THREAD

**Issue by fominik** [histfitter/histfitter#215]
Hi

For some systematics it makes sense to consider the envelope rather than just the up- and down-variations (e.g. scale uncertainties). I have a prototype implementation based on histoSys, so I am wondering if there is an interest in merging it in the main branch (and what checks would be required)?

Cheers
Nikolai

**Comment by longjon929** [comment]
Hi @fominik ,

Thanks, I guess the idea is to automate making the envelope from some set of uncertainties?  That sounds like a nice convenience!  I think it would be reasonable to check that the current tests don't change.  As well as making sure your histograms in the cache are correct and that the systematic is added into the model correctly (eg in xml).  If you have a setup to test doing it manually and with update setup, you could check that you get the same fit result, but that might be a bit cumbersome if you don't have it already.

Best,
Jonathan

**Comment by fominik** [comment]
Hi @longjon929 
I have done the checks suggested, and things seem to be running correctly. 

Cheers
Nikolai

**Comment by longjon929** [comment]
Thanks @fominik , I was busy so I didn't get a chance to look until now.  The test job flagged some space vs tab usage, could you take a look?  

Do you have an example of how to use this?  

Would it be possible to add a systematic that uses this to the test config: https://github.com/histfitter/histfitter/blob/master/test/scripts/config_for_pytest.py#L134?
