### ISSUE TITLE
HistoPlotter norm in ROOT >=6.30

### ISSUE THREAD

**Issue by longjon929** [histfitter/histfitter#217]
Julien and Otilia report changing yields in histoplotter when moving to 6.3

Likeliy due to this:
https://github.com/root-project/root/commit/bb063f72373f075810928361565ba47d66ac6420
and this line:
https://github.com/histfitter/histfitter/blob/56a5a6308b4e86789d0ea9278ad1c77f7643e915/src/HistogramPlotter.cxx#L625

Also check on adding a test to catch a change like this.

**Comment by jln-m** [comment]
I've pointed to the wrong commit, sorry, should have been https://github.com/root-project/root/commit/bb063f72373f075810928361565ba47d66ac6420 instead as a likely source of this change of behaviour of plotOn().
