### ISSUE TITLE
forbiddenFunction in harvestToContours.py

### ISSUE THREAD

**Issue by ericballabene** [histfitter/histfitter#88]
Hi, could we please check this in harvestToContours.py script?
  
https://github.com/histfitter/histfitter/blob/00a673984b8c23a89f2d40967b8ab65354e5f88a/scripts/harvestToContours.py#L446-L447
 
```pytb 
  File "/users2/ballaben/histfitter_v1.0.0/scripts/harvestToContours.py", line 445
    forbiddenFunction = ROOT.TF1(f"forbiddenFunction${value}",args.forbiddenFunction,lowerLimit,upperLimit)
                                                            ^
SyntaxError: invalid syntax
```

Cheers,
Eric

**Comment by matthewfeickert** [comment]
That isn't the result of anything to do with Python 3.6+ f-strings as the syntax is fine

```python
>>> value = 0
>>> print(f"forbiddenFunction${value}")
forbiddenFunction$0
```

and the code snippet there is basically unchanged for over 2 years (c.f. [this git blame](https://github.com/histfitter/histfitter/blame/3361d40ec2e4f0c900a503795e7d1919e6131dd5/scripts/harvestToContours.py#L443-L444)).

The error that you're getting @ericballabene makes it look like you're not using Python 3.6+.

Example:

```
$ docker run --rm -ti python:2.7
Python 2.7.18 (default, Apr 20 2020, 19:27:10) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> value = 0
>>> print(f"forbiddenFunction${value}")
  File "<stdin>", line 1
    print(f"forbiddenFunction${value}")
                                     ^
SyntaxError: invalid syntax
>>> 
```

Can you verify the Python runtime that you're using? What is

```console
$ python --version --version
```
? If you're on a CVMFS machine please also list your environment.

**Comment by ericballabene** [comment]
Hi @matthewfeickert, 

you're right, I forgot to setup a python 3.6+ version in my cluster machine.

Thanks for the help,
Eric

**Comment by matthewfeickert** [comment]
> you're right, I forgot to setup a python 3.6+ version in my cluster machine.

Nice. Glad it was an easy fix. Yeah, when these things still aren't the default on clusters it can be annoying to say the least.
